In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [7]:
l = [1,2,3,"hello"]
l

[1, 2, 3, 'hello']

In [8]:
newArr = np.array(l)
newArr

array(['1', '2', '3', 'hello'], dtype='<U21')

In [9]:
matlist = [[1,2],[3,4],[5,6]]
print(matlist)

[[1, 2], [3, 4], [5, 6]]


In [11]:
matArr = np.array(matlist)
matArr

array([[1, 2],
       [3, 4],
       [5, 6]])

Array Generation

In [13]:
arr = np.arange(0,7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [17]:

mat = np.zeros(6)
mat

array([0., 0., 0., 0., 0., 0.])

In [20]:
mat2d = np.zeros((6,6))
mat2d

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Random Number in NumPy


In [22]:
np.random.rand(10) # random number btwn zero to one

array([0.32534831, 0.45701624, 0.43866359, 0.43858127, 0.53862556,
       0.55054736, 0.43975196, 0.0852512 , 0.48273051, 0.19908792])

In [23]:
np.random.randn(10) #random number btwn -1 to 1

array([ 0.58268033, -1.06711431, -1.47844446, -2.7717989 , -1.01313009,
        2.21981343,  0.02410292, -0.32356045, -1.04332076, -0.28537903])

In [24]:
np.random.randint(10,20,10) # 10 random number betwn 10 to 20

array([19, 10, 19, 17, 16, 10, 11, 18, 17, 18], dtype=int32)

In [26]:
l = [[4,4],[5,5],[6,6]]
mat = np.array(l)
mat

array([[4, 4],
       [5, 5],
       [6, 6]])

In [27]:
mat.size

6

In [28]:
mat.shape

(3, 2)

In [29]:
mat.dtype

dtype('int64')

In [30]:
mat.min()

np.int64(4)

In [31]:
mat.max()

np.int64(6)

In [34]:
mat.sum()

np.int64(30)

In [35]:
mat.mean()

np.float64(5.0)

In [36]:
mat.std()

np.float64(0.816496580927726)

In [37]:
mat.argmax() # gives the index of max. element

np.int64(4)

In [39]:
# Reshape and resize

arr = np.arange(1,31)

arr = arr.reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Arithematic Operations


In [40]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,4,3,2,1])
a3 = a2 + a1
a3

array([6, 6, 6, 6, 6])

In [41]:
a3 -= a2
a3

array([1, 2, 3, 4, 5])

In [43]:
a4 = a2*a1
a4

array([5, 8, 9, 8, 5])